export const DEMO_MATCHES = [
  {
    id: 'demo-match-1',
    sport: 'Padel',
    location: 'F-7 Courts, Islamabad',
    date: 'Sat 20 Apr',
    time: 'Sat 20 Apr 6:00 PM',
    slots: 2,
    filled: 2,
    color: '#00E676',
    status: 'soon',
    createdByName: 'Ali Khan',
  },
  {
    id: 'demo-match-2',
    sport: 'Football',
    location: 'DHA Sports Complex, Lahore',
    date: 'Sun 21 Apr',
    time: 'Sun 21 Apr 8:30 PM',
    slots: 5,
    filled: 6,
    color: '#38BDF8',
    status: 'open',
    createdByName: 'Usman Raza',
  },
  {
    id: 'demo-match-3',
    sport: 'Cricket',
    location: 'Bahria Ground, Rawalpindi',
    date: 'Fri 19 Apr',
    time: 'Fri 19 Apr 9:00 PM',
    slots: 0,
    filled: 11,
    color: '#FB7185',
    status: 'full',
    createdByName: 'Hassan Iqbal',
  },
];

export const DEMO_USERS = [
  {
    id: 'demo-user-1',
    name: 'Ali Khan',
    email: 'ali.demo@proconnect.local',
    city: 'Islamabad',
    role: 'admin',
    banned: false,
    wins: 17,
    sports: ['Padel', 'Futsal'],
    matchesPlayed: 28,
    governmentIdMasked: '****1172',
  },
  {
    id: 'demo-user-2',
    name: 'Sara Fatima',
    email: 'sara.demo@proconnect.local',
    city: 'Lahore',
    role: 'user',
    banned: false,
    wins: 14,
    sports: ['Football'],
    matchesPlayed: 24,
    governmentIdMasked: '****8841',
  },
  {
    id: 'demo-user-3',
    name: 'Zain Qureshi',
    email: 'zain.demo@proconnect.local',
    city: 'Karachi',
    role: 'user',
    banned: true,
    wins: 4,
    sports: ['Cricket'],
    matchesPlayed: 10,
    governmentIdMasked: '****4209',
  },
];

export const DEMO_NOTIFICATIONS = [
  {
    id: 'demo-notif-1',
    type: 'match_confirmation',
    title: 'Match confirmed',
    message: 'Your Padel match at F-7 Courts is confirmed for 6:00 PM.',
    channels: ['push', 'email'],
    status: 'sent',
  },
  {
    id: 'demo-notif-2',
    type: 'proximity_alert',
    title: 'Padel match nearby',
    message: 'A new Padel match opened near your location in Islamabad.',
    channels: ['push', 'email'],
    status: 'queued',
  },
  {
    id: 'demo-notif-3',
    type: 'match_cancellation',
    title: 'Match cancelled',
    message: 'Your Football match was cancelled. You can join another open slot now.',
    channels: ['push', 'email'],
    status: 'sent',
  },
];
